blog/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('19Q2o85a51GPsEtrx/', views.terminal, name='terminal'),
    path('19Q2o85a51GPsEtrx/5p23xqs/', views.spycraft, name='spycraft'),
    path('19Q2o85a51GPsEtrx/5p23xqs/spies', views.spies, name='spies'),
    path('19Q2o85a51GPsEtrx/5p23xqs/agents', views.agents, name='agents'),
    path('19Q2o85a51GPsEtrx/5p23xqs/assets', views.assets, name='assets'),
    path('19Q2o85a51GPsEtrx/5p23xqs/modify', views.modify, name='modify'),
    path('19Q2o85a51GPsEtrx/5p23xqs/encode', views.encode, name='encode'),
    path('19Q2o85a51GPsEtrx/5p23xqs/decode', views.decode, name='decode'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dasset', views.del_asset, name='dasset'),
    path('19Q2o85a51GPsEtrx/5p23xqs/iasset', views.iasset, name='iasset'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dagent', views.del_agent, name='dagent'),
    path('19Q2o85a51GPsEtrx/5p23xqs/iagent', views.iagent, name='iagent'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dspy', views.del_spy, name='dspy'),
    path('19Q2o85a51GPsEtrx/5p23xqs/ispy', views.ispy, name='ispy'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dspy/<spy_id>/', views.delete_spy, name='delete_spy'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dagent/<agent_id>/', views.delete_agent, name='delete_agent'),
    path('19Q2o85a51GPsEtrx/5p23xqs/dasset/<asset_id>/', views.delete_asset, name='delete_asset'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('69420/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('contact/', views.contact_us, name='contact'),
    path('apply-for-visa/', views.visa, name='visa'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/HOMESPY.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "SPYCRAFTCSS.css" %}">
   
</head>



<body style="background-color: #242424 ">
<table>
    <tr>
        <td style="width: 231px;">
            <ul>
                <li><a role="button" href="5p23xqs/spies">Spies</a></li>
                <li><a role="button" href="5p23xqs/agents">Agents</a></li>
                <li><a role="button" href="5p23xqs/assets">Assets</a></li>
                <li><a role="button" href="5p23xqs/modify">Modify Database</a></li>
                <li><a role="button" href="5p23xqs/encode">Encode</a></li>
                <li><a role="button" href="5p23xqs/decode">Decode</a></li>

            </ul>
        </td>
        <td>
            <div class="container">
                {% block content %}{% endblock %}
            </div>

        </td>

    </tr>

</table>

</body>
</html>

templates/LOGINSPY.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Signin</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .btn-primary {
            background-color: green;
            border: 1px solid antiquewhite;
        }

        .btn-primary:hover {
            background-color: white;
            border: 1px solid black;
            color: black;
        }
    </style>

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
</head>
<body class="text-center" style="background-color: #242424; color:white">

<main class="form-signin"
      style="margin: 443px;padding: 20px;border: 1px solid white;border-radius: 89px; margin-top: 41px;margin-bottom: 0px;">
    <form METHOD="POST">
        <img src="https://pngimg.com/uploads/spy/spy_PNG36.png" style="height: 156px;width: 200px;">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal" style="padding: 50px;font-family: initial;font-size: 53px;">Sign in</h1>

        <label for="inputEmail" class="visually-hidden">Email address</label>
        <input type="text" name="naam" id="inputEmail" class="form-control" placeholder="Name" required autofocus>

        <label for="inputPassword">Password</label>
        <input type="text" id="inputPassword" class="form-control" placeholder="id" name="num" required>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
    </form>
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>

templates/agents.html
{% extends 'spycraft.html' %}

{% load static %}

{% block content %}

    <style>
        .tr {
            border: 1px solid #9cfd5a;
            border-collapse: collapse;
            padding: 15px;
            width: 60%;
            margin-left: 30%;
        }

        #t01 tr:nth-child(even) {
            background-color: #eee;
        }

        #t01 tr:nth-child(odd) {
            background-color: #fff;
        }

        #t01 th {
            color: white;
            background-color: black;
        }
    </style>

    <br>
    <br>
    <br>
    <br>

    <table class = "tr" style="color: white; ">
        <tr class = "tr">
            <th style="font-size: 22px; font-family: 'Montserrat Medium'">Code Name</th>
            <th style="font-size: 20px; font-family: 'Montserrat Medium'">Name</th>
            <th style="font-size: 20px; font-family: 'Montserrat Medium'">ID</th>
        </tr>
        {% for agent in agents %}

            <tr class = "tr">
                <th style="color: #4CAF50;font-size: 22px; font-family: 'Montserrat Medium'">{{ agent.code_name }}</th>
                <th style="font-size: 20px; font-family: 'Montserrat Medium">{{ agent.first_name }} {{ agent.last_name }}</th>
                <th style="font-size: 20px; font-family: 'Montserrat Medium">{{ agent.pk }}</th>
            </tr>

        {% endfor %}
    </table>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "custom.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/floating-labels/">
   
    
   
    <link rel="icon" type="image/png" href="{% static "embassy1.png" %}">

    <title>Pakistan Embassy</title>
    <style>
        #topNav{
            z-index:1 ;
        }
        .sticky {
            position: fixed;
            top: 0;
            width: 100%;
            background-color: #e6e6e6;
        }
        .sticky + .content {
            padding-top: 60px;
        }
        .moveICON{
            top:20px ;
        }
        .btn-primary {
            color: #1d9e3b;
            background-color: #f4f7f4;
            border-color: #2d804b;
            border-radius: 8px;
        }
        .btn-primary:hover{
            color:white;
            background-color:rgb(8, 97, 8);
            border-color:rgb(14, 92, 14);;
        }
    </style>

</head>

<body>

    
    
<div class="container" id="icons">
    
    <div style=" width: 113%; height: 50px;font-family: 'Montserrat Medium';text-align:center" class="bg-success text-white">
        <p >Pakistan Embassy, Washington DC </p>
    
        <a style = "position:fixed ;
        top: 16px;
        left: 1059px; color:#fcfbff; " href="https://www.facebook.com/PakistanEmbassyDC" class="fa fa-facebook"></a>
        <a  style = "position:fixed ;
        top: 16px;
        left: 1100px; color:#ebebeb; " href="https://twitter.com/PakEmbassyDC?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" class="fa fa-twitter"></a>
        <a style = "position:fixed ;
        top: 16px;
        left: 1141px; color:#fcfcfc;"href="https://www.facebook.com/PakistanEmbassyDC" class="fa fa-youtube"></a>
    </div>
    
    <!--
    <script>var dt = new Date();
    var time = dt.getHours() + ":" + dt.getMinutes();
    document.write(time);
    </script>
    <img src="http://embassyofpakistanusa.org/wp-content/uploads/2017/12/pak-flag.jpg">
    !-->

    
</div>

<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "embassy.png" %}"
                 alt="Embassy's Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog" target="_blank">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://covid.gov.pk/" target="_blank">COVID-19</a>
                </li>
                <li>
                    <a role="button" class="btn btn-success" href="/apply-for-visa">Apply for Visa</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script>
    window.onscroll = function() {myFunction()};

// Get the navbar
var navbar = document.getElementById("topNav");
//get the icon 
var ic  = document.getElementById("icons");

// Get the offset position of the navbar
var sticky = navbar.offsetTop;


// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
    if (window.pageYOffset >= sticky) {
        navbar.classList.add("sticky")
        ic.classList.add("moveICON")        
    } 
    else {
        navbar.classList.remove("sticky");
        ic.classList.remove("moveICON") 
    }
} 
</script>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "custom.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <!--<link rel="icon" type="image/png" href="{% static "embassy1.png" %}">!-->

    <title>Tradecraft</title>
</head>

<body>

<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "embassy.png" %}"
                 alt="Embassy's Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog" target="_blank">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://covid.gov.pk/" target="_blank">COVID-19</a>
                </li>
                <li>
                    <a role="button" class="btn btn-success" href="/apply-for-visa">Apply for Visa</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/encode.html
{% extends 'spycraft.html' %}

{% load static %}

{% block content %}

    <style>
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #555555;
            color: white;
        }

        .wrapper {

            margin: 0 auto; /* the bottom margin is the negative value of the footer's height */
        }
    </style>

    <br>
    <br>
    <br>
    <br>
    <form>
        <center>
            <input class="wrapper" placeholder="Enter string..." type="text" name="1ac" value="{{ string1 }}"
                   style="height: 250px;width: 600px;background-color: #c6c7be;border: 1px solid darkgray;text-align: center;opacity: 31.4;color: #0d0e01;font-size: 24px;border-radius: 43px;">
            <center>
                <br>
                <div class="wrapper" style="max-width:500px">
                    <center>
                        <button style="opacity:  0.7;background-color: #5b645d;" class="button button1" type="submit" value="Encode">
                            <strong>Submit</strong>
                        </button>
                    </center>
                </div>
                <br>
                <center>
                    <input class="wrapper" placeholder="Result" name="1bc" value="{{ string2 }}"
                           style="height: 250px;width: 600px;background-color: #c6c7be;border: 1px solid darkgray;text-align: center;opacity: 31.4; color: #0d0e01;font-size: 24px;border-radius: 43px;">
                </center>
            </center>
        </center>
    </form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <style>
        h1 {
            text-align: center;
        }

        .button {
            background-color: darkgreen;
            border: none;
            color: white;
            padding: 45px 90px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin: 16px 8px;
            cursor: pointer;
            border-radius: 16px;
        }
    </style>

    <div class="row justify-content-center my-3">
        <div class="col-5">
            <img src="{% static 'embassy1.png' %}" class="img-fluid" alt="">
        </div>
    </div>

    <!-- <div class="row justify-content-center mb-3">
         <div class="col-md-9 text-center">
             <h1 id="hometext" class="font" style="font-size:20px;color:green">Pakistan Embassy, New Delhi</h1>
         </div>
     </div>
     !-->
    <hr>
    <h1>Welcome - خوش آمدید</h1>
    <hr>
    <br>
    <br>
    <br>
    <div class="row center-nav">
        {% for project in projects %}
            
            <div class="card" style="width: 18rem; margin: 45px;">
                <img src="{{project.image.url}}" class="card-img-top" alt="..." style = "height: 285px;">
                <div class="card-body">
                  <h5 class="card-title"> {{ project.title }}</h5>
                  <p class="card-text">{{ project.description }}</p>
                  
                </div>
            </div>
            <!--
            <div class="col-lg-4 col-md-6 align-center">

                {% if project.url %}
                    <a href="{{ project.url }}">
                        <img src="{{ project.image.url }}" class="img-fluid mb-2" alt="">
                    </a>
                {% else %}

                    <img src="{{ project.image.url }}" class="img-fluid mb-2" alt="">
                {% endif %}

                <h3>{{ project.title }}</h3>
                <p>{{ project.description }}</p>

            </div>
            -->
        {% endfor %}
    </div>

    <br>
    <hr>
    <input type=button class="button" style="font-size: 18px"
           onClick="location.href='https://web.citizenportal.gov.pk/'" value="Citizen's Portal">
    <input type=button class="button" style="font-size: 18px"
           onClick="location.href='https://pmo.gov.pk/'" value="Prime Minister's Office">
    <input type=button class="button" style="font-size: 18px"
           onClick="location.href='http://mofa.gov.pk/'" value="Ministry of Foreign Affairs">
{% endblock %}

templates/iasset.html
{% extends 'spycraft.html' %}

{% load static %}

{% block content %}

    <style>
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }

        .wrapper {

            margin: 0 auto; /* the bottom margin is the negative value of the footer's height */
        }

        .bigText {
            height: 30px;
            margin: 0 auto;
        }

        #FORMvisa {
            border-radius: 98px;
            border: 2px solid green;
            width: 54%;
            z-index: 0;
            margin: 95px;
            margin-bottom: 95px;
            margin-bottom: 5px;
        }
    </style>
    <body>
    {% if alert_flag_t %}
        <div class="alert alert-success" role="alert">
            1 record inserted successfully.
        </div>
    {% endif %}
    {% if alert_flag_f %}
        <div class="alert alert-danger" role="alert">
            There was an error in insertion.
        </div>
    {% endif %}
    <center>
        <form id="FORMvisa" name="form" action="{% url "blog:iasset" %}" method="POST">{% csrf_token %}
            <br>
            <br>
            <img src= "https://pngimg.com/uploads/spy/spy_PNG36.png" style="height: 156px;width: 200px;"></img>
            
            <h2 class="mt-5" align="center" style="font-weight: bold ;color:white;">Insert a record</h2>
            <br>
            <br>
            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="First Name" name="first_name"/>
                        <input type="text" placeholder="Last Name" name="last_name"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="Spy ID" name="spy_id"/>
                        <input type="text" placeholder="Asset ID" name="asset_id"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="Codename" name="code_name" style="width: 380px"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <button class="button button1" type="submit" value="Submit">
                        <strong>Submit</strong>
                    </button>
                </center>
            </div>


        </form>
    </center>
    </body>

{% endblock %}

templates/ispy.html
{% extends 'spycraft.html' %}

{% load static %}

{% block content %}

    <style>
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }

        .wrapper {

            margin: 0 auto; /* the bottom margin is the negative value of the footer's height */
        }

        .bigText {
            height: 30px;
            margin: 0 auto;
        }

        #FORMvisa {
            border-radius: 98px;
            border: 2px solid green;
            width: 54%;
            z-index: 0;
            margin: 95px;
            margin-bottom: 95px;
            margin-bottom: 5px;
        }
    </style>
    <body>
    {% if alert_flag_t %}
        <div class="alert alert-success" role="alert">
            1 record inserted successfully.
        </div>
    {% endif %}
    {% if alert_flag_f %}
        <div class="alert alert-danger" role="alert">
            There was an error in insertion.
        </div>
    {% endif %}
    <center>
        <form id="FORMvisa" name="form" action="{% url "blog:ispy" %}" method="POST">{% csrf_token %}
            <br>
            <br>
            <img src= "https://pngimg.com/uploads/spy/spy_PNG36.png" style="height: 156px;width: 200px;">
            <h2 class="mt-5" align="center" style="font-weight: bold ;color:white;">Insert a record</h2>
            <br>
            <br>
            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="First Name" name="first_name"/>
                        <input type="text" placeholder="Last Name" name="last_name"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="Employee ID" name="emp_id"/>
                        <input type="text" placeholder="Spy ID" name="spy_id"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <label>
                        <input type="text" placeholder="Codename" name="code_name" style="width: 380px"/>
                    </label>
                </center>
            </div>

            <br>

            <div class="wrapper" style="max-width:500px;">
                <center>
                    <button class="button button1" type="submit" value="Submit">
                        <strong>Submit</strong>
                    </button>
                </center>
            </div>


        </form>
    </center>
    </body>

{% endblock %}

templates/terminal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/jquery.terminal/js/jquery.terminal.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/jquery.terminal/css/jquery.terminal.min.css"/>
</head>
<body>
<script>

    $.wait = function (ms) {
        var defer = $.Deferred();
        setTimeout(function () {
            defer.resolve();
        }, ms);
        return defer;
    };

    $('body').terminal({
        login: function (user, pass) {
            if (user === 'spy' && pass === 'yps') {
                this.echo('Please wait... You are being redirected.');

                var url = "/blog/19Q2o85a51GPsEtrx/5p23xqs";
                $(location).prop('href', url);
            } else {
                this.echo('Try Again :)');
            }

        }
    }, {
        greetings: 'The door to embassy'
    });
</script>
</body>
</html>